### PR TITLE
comma-separated dash-strings

### PR DESCRIPTION
**Pull request by soli**
Make use of dash-plugin syntax for multi-docset search.

The third commit is not dependent on the two others, it's only more defaults for rust, stylus and tex.

### CODE REVIEW

**Comment by keith** [comment]
Thanks for taking the time to do this! I've cherry picked the third commit here: https://github.com/keith/investigate.vim/commit/b097f21f7c23637487f44f1afc0b9c895e1f4471

**Comment by keith** [comment]
As for the rest of these options I'm not sure that we want to include these in investigate. Since they vary pretty widely and you can combine these locally with Dash, I'd lean towards encouraging users to do that, or setting these in your vim config.

**Comment by soli** [comment]
Well, without the first commit, you need different configurations for machines with old/new versions of Dash [old ones will choke on the comma-separated syntax], so you cannot really do this on the user side.

As far as the recommended settings go, what I like is that these defaults, as advised by https://kapeli.com/dash_plugins will be intersected with the docsets locally installed, resulting in the best possible experience, without having to sync in some weird way your installed docsets and your investigate config.

Moreover, currently there are some hardcoded choices, like "java6", that would benefit from the more general advised defaults.

Of course, this remains up to you…

**Comment by keith** [comment]
Ah I hadn't seen these defaults before. Can you rebase this branch? I think we should merge this.

**Comment by soli** [comment]
I think I just did (but I'm not a git guy, I'm a mercurial guy, so… sorry if I introduced spurious commits…).

**Comment by keith** [comment]
Awesome, thanks a lot for doing this!

**Pull request merged**
